// ─── Top-level node types ─────────────────────────────────────────────────────

/**
 * A text segment of an SMS message body.
 *
 * `text` may contain embedded line breaks (`\n`) — single `\n` represents a
 * line break within a paragraph, double `\n` represents a paragraph boundary.
 */
export type SmsMessageNode = {
  type: 'message'
  /** Raw text content. May contain `\n` characters. */
  text: string
  /**
   * @internal
   * Marks this node as part of the unsubscribe footer.
   * Generated by {@link createUnsubscribeNodes} and by the `::unsubscribe` directive.
   */
  attrs?: { 'is-unsubscribe': true }
}

/**
 * A hyperlink node. `text` holds the URL, which is also used as the display
 * text when rendered in the message body.
 */
export type SmsLinkNode = {
  type: 'link'
  /** The URL. Also used as the display text in the rendered message. */
  text: string
  attrs: {
    /** Whether click tracking is enabled for this link. */
    track: boolean
    /** Whether URL shortening is enabled for this link. */
    shorten: boolean
  }
}

/**
 * Category of an SMS dynamic placeholder.
 *
 * `'Link'` represents special merge-field links such as `[Link:Unsubscribe]`
 * and `[Link:WebBrowser]`.
 */
export type SmsPlaceholderType =
  | 'CustomField'
  | 'Subscriber'
  | 'User'
  | 'RemoteContent'
  | 'Date'
  | 'Link'

/** A dynamic placeholder replaced with subscriber or account data at send time. */
export type SmsPlaceholderNode = {
  type: 'placeholder'
  attrs: {
    /** Category of the placeholder. */
    type: SmsPlaceholderType
    /** Original source token (e.g. `[Subscriber:email]`). */
    original: string
    /** Human-readable display name for the placeholder. */
    name: string
    /** The resolved preview value, or `null` if unavailable. */
    value: string | number | null
    /** Optional maximum character length for the rendered value. */
    'max-length'?: string | null
    /**
     * @internal
     * Marks this node as part of the unsubscribe footer.
     * Generated by {@link createUnsubscribeNodes} and by the `::unsubscribe` directive.
     */
    'is-unsubscribe'?: true
  }
}

/** Union of all node types that can appear in an {@link SmsContentJson} content array. */
export type SmsTopLevelNode = SmsMessageNode | SmsLinkNode | SmsPlaceholderNode

// ─── Root document type ───────────────────────────────────────────────────────

/**
 * The root SMS content JSON document type. This is the shape stored in
 * {@link SmsDocument.content}, returned by {@link smsRfmToJson}, and accepted by
 * {@link validateSmsJson}.
 */
export type SmsContentJson = {
  type: 'sms'
  content: SmsTopLevelNode[]
}

// ─── Validator result types ───────────────────────────────────────────────────

/**
 * A single JSON Schema validation error with a JSON Pointer path.
 */
export type SmsContentValidationError = {
  /** JSON Pointer path to the offending value. Empty string means root. */
  path: string
  /** Human-readable description of the validation failure. */
  message: string
}

/**
 * Discriminated-union result of a non-throwing SMS content validation.
 */
export type SmsContentSafeParseResult<T> =
  | { success: true; data: T }
  | { success: false; errors: SmsContentValidationError[] }
